### ISSUE TITLE
FAN-C via Bioconda has conflict in software version

### ISSUE THREAD

**Issue by JohnGenome** [vaquerizaslab/fanc#75]
Hi dear authors,
I installed FAN-C via Bioconda(py=3.7). And  when i ran the example data through `fanc auto` , the program throws a AttributeError error.

```
2021-09-11 16:51:53,136 INFO FAN-C version: 0.9.0
2021-09-11 16:51:53,141 INFO Output folder: output/
2021-09-11 16:51:53,141 INFO Input files: SRR4271982_chr18_19_1.fastq.gzip, SRR4271982_chr18_19_2.fastq.gzip
2021-09-11 16:51:53,141 INFO Input file types: fastq, fastq
2021-09-11 16:51:53,141 INFO Final basename: fanc_example (you can change this with the -n option!)
2021-09-11 16:51:53,141 INFO Creating output folders...
2021-09-11 16:51:56,445 INFO FAN-C version: 0.9.0
2021-09-11 16:51:56,446 INFO Starting mapping for SRR4271982_chr18_19_1.fastq.gzip
2021-09-11 16:51:56,505 INFO Starting to output alignments to intermediate SAM file /tmp/tmpybky4ylb/intermediate.sam
2021-09-11 16:53:27,109 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_1.bam)
2021-09-11 16:53:53,419 INFO Success, removing intermediate.
2021-09-11 16:53:59,611 INFO FAN-C version: 0.9.0
2021-09-11 16:53:59,613 INFO Starting mapping for SRR4271982_chr18_19_2.fastq.gzip
2021-09-11 16:53:59,659 INFO Starting to output alignments to intermediate SAM file /tmp/tmpxrnhkvnf/intermediate.sam
2021-09-11 16:55:28,831 INFO Converting intermediate SAM file to BAM (output/sam/SRR4271982_chr18_19_2.bam)
2021-09-11 16:55:53,107 INFO Success, removing intermediate.
2021-09-11 16:55:58,104 INFO FAN-C version: 0.9.0
2021-09-11 16:55:58,112 INFO FAN-C version: 0.9.0
2021-09-11 16:56:13,809 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_2.bam with sorted version...
2021-09-11 16:56:14,404 INFO Replacing input SAM/BAM file output/sam/SRR4271982_chr18_19_1.bam with sorted version...
2021-09-11 16:56:20,485 INFO FAN-C version: 0.9.0
2021-09-11 16:56:20,486 INFO Getting genome regions (fragments or bins)
2021-09-11 16:56:20,486 INFO Getting regions
2021-09-11 16:56:28,700 INFO Three arguments detected, assuming SAM/BAM input.
2021-09-11 16:56:28,701 INFO Using filters appropriate for BWA.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "*/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "*/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "*/anaconda3/lib/python3.7/site-packages/fanc/pairs.py", line 169, in _split_sam_worker
    check_sorted=check_sorted):
  File "*/anaconda3/lib/python3.7/site-packages/fanc/tools/files.py", line 420, in split_sam_pairs
    output_file.write(read.to_string() + '\n')
AttributeError: 'pysam.calignedsegment.AlignedSegment' object has no attribute 'to_string'
```
After i check the Release notes of pysam, it seems that to_string() is available for AlignedSegment only after 0.14.0. Besides, for python3.7, the version should be higher than 0.15.0.

So, i tried pysam 0.15.2 or 0.15.3, but none of them has the 'pysam.calignedsegment.AlignedSegment.to_string' attribute. May be deprecated i guess? The software dependency cannot be met anyhow. Is there some suggestiones for users like me without root authority?

**Comment by JohnGenome** [comment]
Sorry for my mistake, after updating pysam to 0.15.2, the `fanc auto` ran properly. So the dependecy is met.
Still i can't figure out why 'pysam.calignedsegment.AlignedSegment.to_string' doesn't work in python.

**Comment by JohnGenome** [comment]
pysam.libcalignedsegment.AlignedSegment.to_string
<method 'to_string' of 'pysam.libcalignedsegment.AlignedSegment' objects>
